"./**/*.js":
  - "yarn eslint_d --fix"
"./**/*.test.ts":
  - "yarn eslint_d --fix"
  - "yarn jest --bail"
"./**/!(*.test).ts":
  - "yarn eslint_d --fix"
  - "yarn jest --bail --findRelatedTests --passWithNoTests"
